name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Testak
      id: testak
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Testak
        setup-command: ''
        command: mvn test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTAK_RESULTS: "${{steps.testak.outputs.result}}"
      with:
        runners: testak
